### ISSUE TITLE
Can't Change the logo and text

### ISSUE THREAD

**Issue by ghost** [BobTheShoplifter/lootvgo-opensource#1]
Hello Bob 
I managed to use your project thank you it helped me a lot but now that I want to change the text or a logo I have an error and the site does not appear anymore I tried to restart all but still nothing I even put the same mistake as before but the site I made if you can help me change the logo. My twitter: https://twitter.com/VGODiamond_gg
Cordialy 
![Capture](https://user-images.githubusercontent.com/38385132/64114854-6aa8ac80-cd8e-11e9-8b8d-5dba85035be4.PNG)

**Comment by ghost** [comment]
The website: vgodiamond.ml

**Comment by RatexIndex** [comment]
> Hello Bob
> I managed to use your project thank you it helped me a lot but now that I want to change the text or a logo I have an error and the site does not appear anymore I tried to restart all but still nothing I even put the same mistake as before but the site I made if you can help me change the logo. My twitter: https://twitter.com/VGODiamond_gg
> Cordialy
> ![Capture](https://user-images.githubusercontent.com/38385132/64114854-6aa8ac80-cd8e-11e9-8b8d-5dba85035be4.PNG)

This is not an Issue watch inside the file and CSS you can also remove SVG and use a PNG.
