### ISSUE TITLE
Session issuee

### ISSUE THREAD

**Issue by snax4a** [BobTheShoplifter/lootvgo-opensource#2]
Hi Bob, I am trying to make steam authentication working
in ```/backend/lib/auth.js``` I have uncommented steam auth strategy, authentication process works properly  new user is inserted, new session record for this steamid is created in session table but when In UI im not logged in.

I am console logging socket.handshake.sessionID in the ```io.on('connection'``` in ```backend/app.js line 337``` but this session ID is different than the one which has been inserted into session table so thats why its not returning user data to the frontend and my session is not authenticated

Do you have any idea why my socket.handshake.sessionID on every page refresh is different i think it should be saved in the cookie and  return proper session ID to the backend

I am using npm run start-windows so this is using local enviroment and frontend is served by express server

**Comment by BobTheShoplifter** [comment]
I have never tested the windows version any way you can set it up on a linux machine?

// With the install script

**Comment by BobTheShoplifter** [comment]
Windows version is now depreciated but might still work
